# Generated by Django 2.2.5 on 2022-01-25 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='recuritment',
        ),
    ]
