# Generated by Django 2.2.5 on 2022-01-25 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0002_remove_board_recuritment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
