# Generated by Django 2.2.5 on 2022-01-26 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0003_auto_20220126_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.User'),
        ),
    ]
