# Generated by Django 2.2.5 on 2022-01-27 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_delete_profile'),
        ('boardapp', '0004_auto_20220126_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=5000, null=True)),
                ('subject', models.CharField(max_length=255)),
                ('last_updated', models.DateField(auto_now_add=True, null=True)),
                ('writter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='userapp.User')),
            ],
        ),
        migrations.CreateModel(
            name='Replys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=5000)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateField(null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='userapp.User')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='userapp.User')),
            ],
        ),
    ]
