# Generated by Django 2.2.5 on 2022-01-27 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0005_board_imgfile'),
        ('boardapp', '0005_replys_topic'),
    ]

    operations = [
    ]
