# Generated by Django 2.2.5 on 2022-01-27 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0006_merge_20220127_1550'),
        ('boardapp', '0006_merge_20220127_1653'),
        ('boardapp', '0006_merge_20220127_1605'),
    ]

    operations = [
    ]
