# Generated by Django 2.2.5 on 2022-01-28 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0007_merge_20220128_0103'),
        ('boardapp', '0007_merge_20220127_1745'),
    ]

    operations = [
    ]
