# Generated by Django 2.2.5 on 2022-01-28 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0007_merge_20220128_0103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='imgfile',
        ),
        migrations.AddField(
            model_name='topic',
            name='imgfile',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='replys',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
