# Generated by Django 2.2.5 on 2022-01-28 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0008_merge_20220128_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replys',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
