# Generated by Django 2.2.5 on 2022-01-28 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0009_auto_20220128_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='imgfile',
        ),
        migrations.AddField(
            model_name='topic',
            name='file',
            field=models.FileField(default=1, upload_to='%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
