# Generated by Django 2.2.5 on 2022-01-28 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0009_auto_20220128_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='imgfile',
        ),
    ]
