# Generated by Django 2.2.5 on 2022-01-28 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0010_auto_20220128_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='file',
            field=models.FileField(upload_to='uploads/', verbose_name='파일'),
        ),
    ]
