# Generated by Django 2.2.5 on 2022-01-28 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0012_auto_20220128_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
