# Generated by Django 2.2.5 on 2022-01-28 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0013_auto_20220128_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='imgtitle',
        ),
        migrations.AlterField(
            model_name='topic',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
