# Generated by Django 2.2.5 on 2022-01-28 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0014_auto_20220128_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='file',
            field=models.FileField(default=1, upload_to='%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
