# Generated by Django 2.2.5 on 2022-01-28 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0015_auto_20220128_1336'),
        ('boardapp', '0010_remove_board_imgfile'),
    ]

    operations = [
    ]
