# Generated by Django 2.2.5 on 2022-01-26 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
