# Generated by Django 2.2.5 on 2022-01-27 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='file',
            field=models.FileField(default='', upload_to='%Y/%m/%d'),
        ),
    ]
