# Generated by Django 2.2.5 on 2022-01-27 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_auto_20220127_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='file',
            field=models.FileField(null=True, upload_to='%Y/%m/%d'),
        ),
    ]
