# Generated by Django 2.2.5 on 2022-01-27 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_auto_20220127_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='file',
            field=models.FileField(default=1, upload_to='%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
