# Generated by Django 2.2.5 on 2022-01-27 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_auto_20220127_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='file',
            field=models.FileField(upload_to='%Y/%m/%d'),
        ),
    ]
