# Generated by Django 2.2.5 on 2022-01-27 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_auto_20220127_1655'),
        ('userapp', '0009_auto_20220127_1542'),
    ]

    operations = [
    ]
