# Generated by Django 2.2.5 on 2022-01-28 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0010_merge_20220127_1745'),
        ('userapp', '0010_merge_20220128_0103'),
    ]

    operations = [
    ]
