# Generated by Django 2.2.5 on 2022-01-24 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('postNum', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
                ('pub_date', models.DateTimeField()),
                ('recuritment', models.BooleanField()),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.User')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('repNum', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=200)),
                ('rep_date', models.DateTimeField()),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.User')),
                ('postNum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.Board')),
            ],
        ),
    ]
