# Generated by Django 2.2.5 on 2022-01-24 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('pw', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=45)),
                ('birth', models.IntegerField()),
                ('mail', models.CharField(max_length=45)),
                ('reportCnt', models.IntegerField(default=0)),
            ],
        ),
    ]
